log:
  level: "debug"
  path: "logs/douyin.log"

mysql:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: "chg123456"
  dbName: "camp"

jwt:
  secret: "?+-31E2~ck8?0mm6jpke$&0xm^43E=-6"

consul:
  host: "127.0.0.1"
  port: 8500

consul-service:
  user:
    name: "user-srv"
    tags: ["douyin", "Yakult", "user", "srv"]
  feed:
    name: "feed-srv"
    tags: ["douyin", "Yakult", "feed", "srv"]
  favorite:
    name: "favorite-srv"
    tags: ["douyin", "Yakult", "favorite", "srv"]
  comment:
    name: "comment-srv"
    tags: ["douyin", "Yakult", "comment", "srv"]

consul-web:
  user:
    name: "user-web"
    tags: ["douyin", "Yakult", "user", "web"]
    port: 8021
  feed:
    name: "feed-web"
    tags: ["douyin", "Yakult", "feed", "web"]
    port: 8022
  favorite:
    name: "favorite-web"
    tags: ["douyin", "Yakult", "favorite", "web"]
    port: 8023
  comment:
    name: "comment-web"
    tags: ["douyin", "Yakult", "comment", "web"]
    port: 8024